limit IDE versions for runPluginVerifier
IU-2023.2 (not yet released) fails with
Plugin com.premiumminds.datagripvaultplugin:1.2.1 against IU-232.8453.116: 2 compatibility problems. 1 usage of scheduled for removal API. 29 usages of internal API
Compatibility problems (2):
    #Invocation of unresolved method com.intellij.database.dataSource.url.ui.UrlPropertiesPanel.createLabelConstraints(int, int, double) : GridConstraints
        Constructor com.premiumminds.datagrip.vault.VaultWidget.<init>() contains an *invokestatic* instruction referencing an unresolved method com.intellij.database.dataSource.url.ui.UrlPropertiesPanel.createLabelConstraints(int, int, double) : com.intellij.uiDesigner.core.GridConstraints. This can lead to **NoSuchMethodError** exception at runtime.
        The method might have been declared in the super interface: com.intellij.openapi.Disposable
    #Invocation of unresolved method com.intellij.database.dataSource.url.ui.UrlPropertiesPanel.createSimpleConstraints(int, int, int) : GridConstraints
        Constructor com.premiumminds.datagrip.vault.VaultWidget.<init>() contains an *invokestatic* instruction referencing an unresolved method com.intellij.database.dataSource.url.ui.UrlPropertiesPanel.createSimpleConstraints(int, int, int) : com.intellij.uiDesigner.core.GridConstraints. This can lead to **NoSuchMethodError** exception at runtime.
        The method might have been declared in the super interface: com.intellij.openapi.Disposable